version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
